#!/bin/bash

while true ; do

# Check the current date. If it's the 28th of the month, exit the loop and continue. 
until date +%d | grep -q 28 ; do
	today=`date`
	echo "$today - Not the 28th yet..."
	sleep 86400
done

# Establish the current month, numerically.
month=`date +%m`

# Set the will_file. This file could be any file that is ONLY modifiable by the user. 
# This means no group permissions, and preferably kept inside a write protected directory, 
# like the /root/ folder.
will_file='PATH/TO/WILL_FILE'


# Establish the numerical month of when the user last checked in. This is the most important part, so
# triple check that this command works on your machine before using it.
# It is only valid if we assume that the 'will_file' cannot be modified by ANYONE else but the user of the will.
willCookie=`stat -c %y $will_file | grep -o "\-[0-9][0-9]-" | grep -o [0-9][0-9]`


# If the user hasn't checked in... He's probably dead. So:
if ! [ "$month" == "$willCookie" ] ; then
	# Do some stuff here
	# Be sure to thoroughly test any code you enter here, because if it doesn't work, your heirs are boned.
	echo "Looks like you're dead! Sending last will..."

	# You could perfrom an `exit` here, but if the server's internet connection happens to fail at the
	# exactly wrong time, the bot would exit and no data would be sent, ever. 
	# Adding a delay timer means the script will try again in a few hours.
	sleep 10000

fi

# If the user HAS checked in, he's alive. Keep calm and carry on!
echo "Another month successfully alive!"
sleep 86400

done
